version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - .docker/redis/data:/data
    command:
      - /bin/sh
      - -c
      - 'redis-server --save 30 1 --requirepass 1234'
    restart: always
    
volumes:
  db:
    driver: local